<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Duende.IdentityModel.OidcClient" />
    <PackageReference Include="Humanizer" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" VersionOverride="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenIdConnectClient.Models\OpenIdConnectClient.Models.csproj" />
  </ItemGroup>

</Project>
